name: Live build action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]

jobs:
  aarch64_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 arrch64
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: stretch

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
                 
          shell: /bin/sh
          
          install: |
            apt-get update -q -y
            apt-get install -q -y git live-build simple-cdd cdebootstrap curl
     
          # Set an output parameter `uname` for use in subsequent steps
          run: |
            ./build.sh --live --variant
            ls -al
            cp images/* "/artifacts/"

      - name: Show the artifact
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          ls -al "${PWD}/artifacts"
